import 'package:flutter/widgets.dart';

import '../../../../core/localization/app_translator.dart';

String orderText(BuildContext context, String arabic) {
  if (Localizations.localeOf(context).languageCode == 'fr') {
    return _french[arabic] ?? arabic;
  }
  return AppTranslator.translate(context, arabic);
}

const Map<String, String> _french = <String, String>{
  'الطلبات': 'Commandes',
  'قائمة الطلبات': 'Liste des commandes',
  'تحديث الطلبات': 'Actualiser les commandes',
  'الفلاتر': 'Filtres',
  'تطبيق الفلاتر': 'Appliquer les filtres',
  'مسح الفلاتر': 'Effacer les filtres',
  'بحث': 'Recherche',
  'ابحث باسم الزبون أو Player ID': 'Rechercher par client ou Player ID',
  'حالة الطلب': 'Statut de la commande',
  'حالة الدفع': 'Statut du paiement',
  'طريقة الدفع': 'Mode de paiement',
  'اللعبة': 'Jeu',
  'العرض': 'Offre',
  'الكل': 'Tous',
  'من تاريخ': 'À partir du',
  'إلى تاريخ': 'Jusqu’au',
  'تحميل المزيد': 'Charger plus',
  'لا توجد طلبات.': 'Aucune commande.',
  'لا توجد نتائج مطابقة للفلاتر الحالية.':
      'Aucun résultat ne correspond aux filtres actuels.',
  'لا يوجد اتصال بالمنصة.': 'Connexion à la plateforme indisponible.',
  'تعذر تحميل الطلبات.': 'Impossible de charger les commandes.',
  'إعادة المحاولة': 'Réessayer',
  'البيانات المعروضة قديمة.': 'Les données affichées sont obsolètes.',
  'طلب': 'Commande',
  'فتح تفاصيل الطلب': 'Ouvrir les détails de la commande',
  'تحميل تفاصيل الطلب': 'Chargement des détails de la commande',
  'تعذر تحميل تفاصيل الطلب.':
      'Impossible de charger les détails de la commande.',
  'الطلب غير موجود.': 'Commande introuvable.',
  'تعذر العثور على هذا الطلب أو لم يعد متاحًا.':
      'Cette commande est introuvable ou n’est plus disponible.',
  'انتهت جلسة المنصة.': 'La session de la plateforme a expiré.',
  'ملخص الطلب': 'Résumé de la commande',
  'بيانات الزبون واللاعب': 'Client et joueur',
  'السعر والحالات': 'Prix et statuts',
  'معلومات الاتصال': 'Coordonnées',
  'الرسالة العامة': 'Message public',
  'تواريخ الطلب': 'Dates de la commande',
  'التسلسل الزمني': 'Chronologie',
  'لا توجد أحداث عامة للطلب.': 'Aucun événement public pour cette commande.',
  'الزبون': 'Client',
  'معرّف اللاعب': 'Player ID',
  'الاسم داخل اللعبة': 'Nom dans le jeu',
  'وحدة المكافأة': 'Unité de récompense',
  'الكمية': 'Quantité',
  'السعر': 'Prix',
  'دج': 'DZD',
  'وقت الإنشاء': 'Créée le',
  'آخر تحديث': 'Dernière mise à jour',
  'وقت الاكتمال': 'Terminée le',
  'بدء الاسترداد': 'Remboursement commencé le',
  'وقت الاسترداد': 'Remboursée le',
  'البريد الإلكتروني': 'E-mail',
  'رقم الهاتف': 'Téléphone',
  'يوجد إثبات دفع': 'Preuve de paiement disponible',
  'لا يوجد إثبات دفع': 'Aucune preuve de paiement',
  'نقدًا': 'Espèces',
  'تحويل': 'Virement',
  'جديد': 'Nouvelle',
  'مقبول': 'Acceptée',
  'قيد المعالجة': 'En traitement',
  'مكتمل': 'Terminée',
  'مرفوض': 'Refusée',
  'ملغى': 'Annulée',
  'بانتظار الدفع': 'En attente de paiement',
  'قيد المراجعة': 'En cours de vérification',
  'مدفوع': 'Payée',
  'إثبات مرفوض': 'Preuve refusée',
  'استرداد معلق': 'Remboursement en attente',
  'مسترد': 'Remboursée',
  'إنشاء الطلب': 'Commande créée',
  'تغيير حالة الطلب': 'Statut de commande modifié',
  'تغيير حالة الدفع': 'Statut de paiement modifié',
  'إرفاق إثبات الدفع': 'Preuve de paiement jointe',
  'اكتمال الاسترداد': 'Remboursement terminé',
  'إلغاء': 'Annuler',
};
